apiVersion: v1
kind: Service
metadata:
  labels:
    app: samba-ad
  name: samba-ad
spec:
  ports:
  - name: sambaad
    port: 389
    protocol: TCP
    targetPort: 389
  selector:
    app: samba-ad
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: samba-ad
  name: samba-ad
spec:
  replicas: 1
  selector:
    matchLabels:
      app: samba-ad
  template:
    metadata:
      labels:
        app: samba-ad
    spec:
      containers:
      - image: tli551/samba-ad:v0.1.0
        imagePullPolicy: IfNotPresent
        name: samba-ad
        securityContext:
          privileged: true
          runAsUser: 0
        env:
        - name: REALM
          value: "example.org"
        - name: DOMAIN
          value: "EXAMPLE"
        - name: ADMIN_PASSWD
          value: "Passw0rd"
        - name: USER_COUNT
          value: "5"
