#!/bin/sh

GREEN='\e[0;32m'
NC='\e[0m'

startIndex=${1}
noofusers=${2}
if [ -z "${startIndex}" ] || [ -z "${noofusers}" ]; then
  echo -e "${GREEN}Please provide start index and no of users to add${NC}"
  echo "Usage:"
  echo "    ${0} <startIndex> <noofusers>"
  echo ""
  echo -e "For example: ${GREEN}${0} 5 3${NC}"
  echo "   This command will add johndoe5, johndoe6, johndoe7 to Active Directory"
  echo "   All user passwords will be the same as the admin password"
  exit 0
fi

noofusers=$((startIndex + noofusers))
SEARCH_DOMAIN=$(echo "${REALM}" | tr [:upper:] [:lower:])
SEARCH_BASE=$(echo dc=${SEARCH_DOMAIN} | sed "s/\./,dc=/g")

counter=$(( startIndex ))
while [ "$counter" -lt ${noofusers} ]; do
  samba-tool user create johndoe${counter} --given-name John${counter} --surname Doe${counter} \
    --mail-address johndoe${counter}@mail.${SEARCH_DOMAIN} --random-password
  samba-tool user setpassword johndoe${counter} --newpassword=${ADMIN_PASSWD} -U administrator --password ${ADMIN_PASSWD} >/dev/null 2>&1
  counter=$((counter + 1))
done

ldapsearch -xLLL -D "cn=administrator,cn=users,${SEARCH_BASE}" -w "${ADMIN_PASSWD}" -b "cn=users,${SEARCH_BASE}" -s sub "givenName=John*"

echo ""
