name: Multiarch build

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

  workflow_dispatch:

env:
  IMAGE_NAME: samba-ad
  IMAGE_TAG: v0.2.0
  DH_REGISTRY: docker.io
  DH_NAMESPACE: tli551

jobs:
  build:
    name: Build and push multi-arch image
    runs-on: ubuntu-20.04
    
    steps:
      - uses: actions/checkout@v3
        
      - name: set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: login to DockerHub
        uses: docker/login-action@v2
        with:
          registry: ${{ env.DH_REGISTRY }}
          username: ${{ secrets.DH_USER }}
          password: ${{ secrets.DH_KEY }}

      - name: build and push images
        run: |
          docker buildx build --push \
            --tag ${{ env.DH_REGISTRY }}/${{env.DH_NAMESPACE }}/${{env.IMAGE_NAME}}:${{env.IMAGE_TAG}} \
            --platform linux/amd64,linux/arm64 .

      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ secrets.DH_USER }}
          password: ${{ secrets.DH_KEY }}
          repository: ${{env.DH_NAMESPACE }}/${{env.IMAGE_NAME}}
